name: Daily Automated Commit

on:
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Email 24f2002054@ds.study.iitm.ac.in - Create daily update
        run: |
          echo "Daily update on $(date)" >> daily-log.txt
          echo "Automated commit by GitHub Actions" >> daily-log.txt
          echo "---" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add daily-log.txt
          git commit -m "Daily automated update - $(date +'%Y-%m-%d %H:%M:%S UTC')" || exit 0
          git push
